apiVersion: apps/v1 
kind: Deployment
metadata:
  name: priviledged
  labels:
    app: ubuntu
spec:
  selector:
    matchLabels:
      app: priviledged
  template:
    metadata:
      labels:
        app: priviledged
    spec:
      containers:
      - name: ubuntu
        image: ubuntu:18.04
        ports:
        - containerPort: 22
        securityContext:
          privileged: true

