apiVersion: apps/v1 
kind: Deployment
metadata:
  name: secret
  labels:
    app: secret
spec:
  selector:
    matchLabels:
      app: secret
  template:
    metadata:
      labels:
        app: secret
    spec:
      containers: 
      - name: ubuntu
        image: ubuntu:18.04
        env:
            - name: AWS_SECRET_ACCESS_KEY
              value: "abcdefg"

